export const jwtConstants = {
    secret: ' IGLIYGLIGIUGIUYGIHGLGIU YGIGYV6UYGTK,JHVUYTFRPICYT UYGFIYHGIT9PUB IYGF;OUHHC8YGOU GFH;KHV7YT98UB YGTIY HYGFIUB VHFDKHGBCFOHB C97UHKFP8H.JBGFOUJB JGYTPIKBH',
  };